Fix .deb builds
The code triggers following error:
abisip-find.c:317:3: error: format not a string literal and no format
arguments [-Werror=format-security]

The error was introduced in 5bf1e15c55340f236d84f70d3d04c871403d3503.

Change-Id: I613781495edbc53916ca70ff7b78d28ffabd3f5d